[versions]
kotlin = "2.3.0"
ktor = "3.1.3"
kotlinx-datetime = "0.6.2"
kotlinx-serialization = "1.8.1"
kaml = "0.79.0"
logback = "1.5.13"
dotenv = "4.0.0"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dotenv = { id = "co.uzzu.dotenv.gradle", version.ref = "dotenv" }

[libraries]
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-swagger = { module = "io.ktor:ktor-server-swagger", version.ref = "ktor" }
ktor-server-testHost = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime"}
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization"}
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }

logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
